# Generated by Django 4.2.2 on 2023-06-17 14:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_order_product_price_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='order_price',
        ),
    ]
