# Generated by Django 4.2.2 on 2023-06-17 15:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_order_product_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='product_price',
        ),
    ]
