# Generated by Django 4.2.2 on 2023-06-17 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_remove_order_product_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='product_price',
            field=models.IntegerField(default=0),
        ),
    ]
